var locations = [

{id:["1214417"],newlocs:["Scottsdale, AZ","Mesa, AZ","Tempe, AZ","Chandler, AZ","Gilbert, AZ","Glendale, AZ","Peoria, AZ","Tolleson, AZ","Avondale, AZ","Litchfield Park, AZ"]},
{id:["1215717"],newlocs:["Indianapolis, IN","Muncie, IN","Pendleton, IN","Fishers, IN","Luxhaven, IN","Fortville, IN","Noblesville, IN","Carmel, IN","Greenfield, IN"]},
{id:["1215703"],newlocs:["Des Moines, IA","West Des Moines, IA","Urbandale, IA","Waukee, IA","Clive, IA","Ankeny, IA","Waukee, IA","Altoona, IA","Bondurant, IA"]},
{id:["1215706"],newlocs:["Naperville, IL","North Aurora, IL","Warrenville, IL","Downers Grove, IL","Lisle, IL","Woodridge, IL","Wheaton, IL","Lombard, IL","Oakbrook, IL","Elmhurst, IL"]},
{id:["1215786"],newlocs:["Sikeston, MO","Dexter, MO","Poplar Bluff, MO","Cape Girardeau, MO","Idalia, MO","Scott City, MO","Fredericktown, MO"]},
{id:["1215787"],newlocs:["St Louis, MO","Bonne Terre, MO","Farmington, MO","Perryville, MO","Park Hills, MO","Festus, MO","Barnhart, MO","Arnold, MO","Mehlville, MO","Columbia, IL"]},
{id:["1215796"],newlocs:["Franklin, KY","Russellville, KY"]},
{id:["1215709"],newlocs:["Orland Park, IL","Oak Lawn, IL","Tinley Park, IL","Burr Ridge, IL","Palos Hills, IL","Burbank, IL"]},
{id:["1215707"],newlocs:["Palatine, IL","Arlington Heights, IL","Barrington, IL","Deerfield, IL","Northbrook, IL","Glenview, IL","Vernon Hills, IL","Lincolnshire, IL","Mt Prospect, IL","Wheeling, IL"]},
{id:["1215704"],newlocs:["Waterloo, IA","Evansdale, IA","Gilbertville, IA","Hudson, IA"]},
{id:["1215530"],newlocs:["North Liberty, IA","Iowa City, IA","Marion, IA","Hiawatha, IA","Mt Vernon, IA","Solon, IA"]},
{id:["1214532"],newlocs:["Naperville, IL","Oak Park, IL","Elmhurst, IL","Evanston, IL","Skokie, IL","Des Plaines, IL","Park Ridge, IL","Rosemont, IL","Schaumburg, IL","Arlington Heights, IL"]},
{id:["1215542"],newlocs:["Bettendorf, IA","Moline, IL","Rock Island, IL","Eldridge, IA","LeClaire, IA","Walcott, IA" ]},
{id:["1214832"],newlocs:["Aurora, CO","Littleton, CO","Englewood, CO","Centennial, CO","Lakewood, CO","Highlands Ranch, CO","Westminster, CO","Arvada, CO","Wheat Ridge, CO","Broomfield, CO" ]},
{id:["1215534"],newlocs:["Galena, IL","Peosta, IA","Dyersville, IA","Farley, IA","Epworth, IA" ]},
{id:["1215710"],newlocs:["Bettendorf, IA","Moline, IL","Rock Island, IL","Eldridge, IA","LeClaire, IA","Walcott, IA" ]},
{id:["1215808"],newlocs:["Altoona, WI","Lake Hallie, WI","Chippewa Falls, WI" ]},
{id:["1215712"],newlocs:["South Elgin, IL","St Charles, IL","Geneva, IL","West Dundee, IL","Carpentersille, IL" ]},
{id:["1215753"],newlocs:["Denver, CO","Aurora, CO","Littleton, CO","Englewood, CO","Centennial, CO","Lakewood, CO","Highlands Ranch, CO","Westminster, CO","Arvada, CO","Wheat Ridge, CO" ]},
{id:["1215801"],newlocs:["Cincinnati, OH","Florence, KY","Oakbrook, KY","Independence, KY","Taylor Mill, KY" ]},
{id:["1215785"],newlocs:["Fort Mitchell, KY","Cincinnati, OH","Florence, KY","Oakbrook, KY","Independence, KY","Taylor Mill, KY" ]},
{id:["1215620"],newlocs:["Scottsdale, AZ","Mesa, AZ","Tempe, AZ","Chandler, AZ","Gilbert, AZ","Phoenix, AZ","Peoria, AZ","Tolleson, AZ","Avondale, AZ","Litchfield Park, AZ" ]},
{id:["1215750"],newlocs:["Aurora, CO","Littleton, CO","Englewood, CO","Centennial, CO","Lakewood, CO","Highlands Ranch, CO","Westminster, CO","Arvada, CO","Wheat Ridge, CO","Denver, CO" ]},
{id:["1215737"],newlocs:["Scottsdale, AZ","Mesa, AZ","Tempe, AZ","Chandler, AZ","Gilbert, AZ","Phoenix, AZ","Peoria, AZ","Tolleson, AZ","Avondale, AZ","Litchfield Park, AZ" ]},
{id:["1215751"],newlocs:["Fort Collins, CO","Loveland, CO","Windsor, CO" ]},
{id:["1215713"],newlocs:["Schaumburg, IL","Hoffman Estates, IL","Elk Grove Village, IL","Carol Stream, IL","Glendale Heights, IL","Medinah, IL" ]},
{id:["1214549"],newlocs:["Muncie, IN","Pendleton, IN","Fishers, IN","Luxhaven, IN","Fortville, IN","Noblesville, IN","Carmel, IN","Greenfield, IN","Zionsville, IN","McCordsville, IN" ]},
{id:["1215719"],newlocs:["Louisville, KY","St Matthews, KY","Middletown, KY","Jeffersontown, KY" ]},
{id:["1215708"],newlocs:["New Lenox, IL","Frankfort, IL","Bolingbrook, IL","Plainfield, IL","Romeoville, IL" ]},
{id:["1215807"],newlocs:["Henderson, NV"]},
{id:["1215762"],newlocs:["Kansas City, MO","Independence, MO","Overland Park, KS","Olathe, KS" ]},
{id:["1215804"],newlocs:["Frankfort, KY","Louisville, KY"]},
{id:["1215760"],newlocs:["Aurora, CO","Denver, CO","Englewood, CO","Centennial, CO","Lakewood, CO","Highlands Ranch, CO","Westminster, CO","Arvada, CO","Wheat Ridge, CO","Broomfield, CO" ]},
{id:["1215788"],newlocs:["St Matthews, KY","Middletown, KY","Jeffersontown, KY","Shively, KY","Ashville, KY","Prairie Village, KY","Greenwood, KY" ]},
{id:["1215744"],newlocs:["Scottsdale, AZ","Mesa, AZ","Tempe, AZ","Chandler, AZ","Gilbert, AZ","Glendale, AZ","Peoria, AZ","Tolleson, AZ","Avondale, AZ","Litchfield Park, AZ" ]},
{id:["1214550"],newlocs:["Waukesha, WI","Menomonee Falls, WI","Brookfield, WI","New Berlin, WI","Greendale, WI" ]},
{id:["1215705"],newlocs:["Bettendorf, IA","East Moline, IL","Davenport, IA","Rock Island, IL" ]},
{id:["1215820"],newlocs:["Salt Lake City, UT","Ogden, UT" ]},
//{id:["1215806"],newlocs:[]},
{id:["1214543"],newlocs:["Kansas City, MO","Independence, MO","Lenexa, KS","Olathe, KS"]},
{id:["1215814"],newlocs:["Truckee, CA","Tahoe City, CA" ]},
{id:["1215714"],newlocs:["Naperville, IL","Oak Park, IL","Elmhurst, IL","Evanston, IL","Skokie, IL","Des Plaines, IL","Park Ridge, IL","Rosemont, IL","Chicago, IL","Arlington Heights, IL" ]},
{id:["1215745"],newlocs:["Phoenix, AZ","Mesa, AZ","Tempe, AZ","Chandler, AZ","Gilbert, AZ","Glendale, AZ","Peoria, AZ","Tolleson, AZ","Avondale, AZ","Litchfield Park, AZ" ]},
{id:["1215817"],newlocs:["Provo, UT","Orem, UT" ]},
{id:["1215789"],newlocs:["Kansas City, MO","Independence, MO","Overland Park, KS","Olathe, KS" ]},
{id:["1215781"],newlocs:["Bloomsdale, MO","Bonne Terre, MO","Farmington, MO","Perryville, MO","Park Hills, MO","Festus, MO","Barnhart, MO","Arnold, MO","Mehlville, MO","Columbia, IL" ]},
{id:["1215619"],newlocs:["Scottsdale, AZ","Mesa, AZ","Phoenix, AZ","Chandler, AZ","Gilbert, AZ","Glendale, AZ","Peoria, AZ","Tolleson, AZ","Avondale, AZ","Litchfield Park, AZ" ]},
{id:["1215770"],newlocs:["Kansas City, MO","Lawrence, KS","Pauline, KS","Berryton, KS" ]},
{id:["1215621"],newlocs:["Sierra Vista, AZ","Sahaurita, AZ" ]},
{id:["1215526"],newlocs:["Cedar Falls, IA","Evansdale, IA","Gilbertville, IA","Hudson, IA" ]},
{id:["1215818"],newlocs:["Stevens Point, WI","Weston, WI" ]},
{id:["1215819"],newlocs:["Salt Lake City, UT","Ogden, UT","West Jordan, UT","Sandy, UT","Taylorsville, UT","West Valley City, UT" ]},
{id:["1215755"],newlocs:["Englewood, CO","Aurora, CO","Littleton, CO","Englewood, CO","Centennial, CO","Lakewood, CO","Highlands Ranch, CO","Westminster, CO","Arvada, CO","Wheat Ridge, CO" ]},
{id:["1215715"],newlocs:["Elk Grove Village, IL","Itasca, IL","Addison, IL","Bensenville, IL","Schiller Park, IL","Franklin Park, IL"]},

];